export const IMAGE_SEARCH_DONE  = "IMAGE_SEARCH_DONE";
export const IMAGE_SEARCH_LOAD_DONE  = "IMAGE_SEARCH_LOAD_DONE";
export const IMAGE_FAVE_DONE  = "IMAGE_FAVE_DONE";
export const IMAGE_FAVE_REMOVED = "IMAGE_FAVE_REMOVED";
export const ADD_KEYWORD  = "ADD_KEYWORD";